### ISSUE TITLE
Problem importing pixi-spine using pixi 5

### ISSUE THREAD

**Issue by diegoclerici** [pixijs/pixi-spine#297]
Hi. Before we migrate from Pixi v4 to v5, we had this code running: 

```
import * as PIXI from 'pixi.js'; 
import '../../../libs/pixi-spine/pixi-spine.js' //local lib
```
But when we upgrade to Pixi v5 we get this error: 

`"export 'spine' (imported as 'PIXI') was not found in 'pixi.js'
`

We found [this solution](https://github.com/pixijs/pixi-spine/issues/263) and make this changes: 

```
import 'pixi.js';
import 'pixi-spine';
```

And now we are getting: 

```
ReferenceError: PIXI is not defined
(anonymous function)
node_modules/pixi-spine/bin/pixi-spine.js:6897
  6894 |         return _this;
  6895 |     }
  6896 |     return SpineSprite;
  6897 | }(PIXI.Sprite));
  6898 | pixi_spine.SpineSprite = SpineSprite;
  6899 | var SpineMesh = (function (_super) {
  6900 |     __extends(SpineMesh, _super);
```

We are stuck. Any suggestions ?

Thank you.

**Comment by ivanpopelyshev** [comment]
```
/* global __dirname, require, module*/
const path = require('path');
const webpack = require('webpack');

const config = {
  entry: {
    test: __dirname + '/src/index.js'
  },
  devtool: 'source-map',
  output: {
    path: __dirname + '/public/js',
    filename: "[name].js",
    publicPath: '/js/'
  },
  module: {
    rules: [
      {
        test: /(\.jsx|\.js)$/,
        loader: 'babel-loader',
        exclude: /(node_modules)/
      },
      {
        test: /(\.jsx|\.js)$/,
        loader: 'eslint-loader',
        exclude: /node_modules/
      }
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      PIXI: 'pixi.js'
    })
  ],
  resolve: {
    modules: [path.resolve('./node_modules'), path.resolve('./src')],
    extensions: ['.json', '.js', '.jsx']
  },
};

module.exports = [config];
```

need script-loader

**Comment by diegoclerici** [comment]
Hi @ivanpopelyshev ! Thank you. I forgot to mention that we are using create-react-app.. So we cannot add PIXI with providePlugin. 

It's planned to remove dependency for PIXI as global in a future ? 

We really apreciate your time any other suggestion from you it's welcome. Thank you!

**Comment by ivanpopelyshev** [comment]
Yes, we'll do it, I think it possible to separate a build into two bundles: "lib" and "global". 

The problem is that "lib" doesn't work well with our typescript definitions, and to make it consistent we have to make pixijs lib typings.

**Comment by diegoclerici** [comment]
Ok. We have no extra time to help now. We are migrating an app from Flash to React/PixiJs, and PIXI.Spine is very useful for our "animated images" 

Thank you, we hope you can release this feature soon.

**Comment by ivanpopelyshev** [comment]
Oh! I'm moving 1 mln lines of code app from flash with all swf vectors and a bit of stage3d :) Do you need any tips?

**Comment by lucas-jones** [comment]
I've made a more Typescript / ES6 friendly fork of the `pixi-spine` as a proof of concept. As I've had a few issues with the current implementation. It also removes the use of global PIXI

https://github.com/lucas-jones/pixi-spine

**Comment by ivanpopelyshev** [comment]
@lucas-jones 
OK, I will look at it this weekend, and @bigtimebuddy will help me to put it in main repo. Need to check everything ;)

**Comment by diegoclerici** [comment]
Thank you @lucas-jones and @ivanpopelyshev . Great job! I've will waiting!

**Comment by lucas-jones** [comment]
Ideally `pixi-spine` would use the [spine-ts](https://github.com/EsotericSoftware/spine-runtimes) runtimes as an npm package and this package wouldn't need to include / have a clone of it (`src/core/..`).

**Comment by ivanpopelyshev** [comment]
We cant use it, because of extra hacks for textures and matrices stuff , I also support some legacy features about events. 

Yes, there are problems when I take stuff from upstream I can make something wrong.

At the same time, I help spine-ts many times because I review every commit :) I'm sure @badlogic likes that.

**Comment by doup** [comment]
I'm using Parcel and in my case this ugly hack has made the trick:
```
import * as PIXI from 'pixi.js';
window.PIXI = PIXI;
import 'pixi-spine';
```

**Comment by lucas-jones** [comment]
Any update on this with the ES6 imports? :)

**Comment by ivanpopelyshev** [comment]
@lucas-jones thanks for reminding.

**Comment by Friksel** [comment]
Yes, Es6 imports would be very much appreciated indeed! Next to the modular approach my guess is  Webpack will include the full PIXI lib instead of using treeshaking when using the ProvidePlugin, so that would probably also make the output a lot bigger than needed.

**Comment by rvanderspuy** [comment]
This is what worked for me (Pixi 5, spine 3.8 + webpack):

```
import * as PIXI from "pixi.js";
window.PIXI = PIXI;
require("pixi-spine")
```

I'm getting an error, `"export 'spine' (imported as 'PIXI') was not found in 'pixi.js'` - but maybe that's not important?

**Comment by ivanpopelyshev** [comment]
Ugh, right, i still have to look at @lucas-jones version. Thanks for reminding!

**Comment by lucas-jones** [comment]
I'm happy to help if needed :)

From what I remember it's mainly
- Removing `namespace pixi_spine`
- Switching the imports to ES6 style, `import { Loader } from "pixi.js";` -> `PIXI.LoaderResource`

**Comment by qtiki** [comment]
I just ran into this again while upgrading our build pipeline to include Babel. Earlier our pipeline only included TypeScript and Webpack and I had it working with the same workaround in place that @doup used for Parcel. With Babel this no longer worked but I managed to get it working by using the ProvidePlugin as suggested - but I still see the same warnings that @rvanderspuy mentioned so it's not an optimal solution.

**Comment by ivanpopelyshev** [comment]
We are going for a new way to build Pixi with TS and plugins at the same time - I dont think I will merge it to plugin before the situation with PixiJS itself gets resolved.

**Comment by Gawainli** [comment]
Thanks! @doup and @rvanderspuy 
it fix my issue
(pixi5 + parcel)

**Comment by brettstack** [comment]
```js
import * as PIXI from 'pixi.js'
import 'pixi-spine'

window.PIXI = PIXI
```

Reference it using `window.PIXI.spine.Spine`, otherwise, you'll still get the `export 'spine' (imported as 'PIXI') was not found in 'pixi.js'` error.

**Comment by rvanderspuy** [comment]
@brettstack Thanks! 

In that example, what should be referenced as `window.PIXI.spine.Spine` ?

**Comment by lucas-jones** [comment]
Any update on this? :)

**Comment by ivanpopelyshev** [comment]
@lucas-jones All news are related to main pixi repo

When we complete TS conversion, i'll convert all plugins to es6 modules and make a tutorial for vanilla guys on how to make their own bundle with plugins, and generate `d.ts` file for project

We also have a solution for overrides like we do for `IMetadata` -global mixins!

https://github.com/pixijs/pixi.js/pull/6472

**Comment by lucas-jones** [comment]
Awesome, Cheers Ivan 😄

**Comment by skylarrikin** [comment]
Heya @lucas-jones 
> I've made a more Typescript / ES6 friendly fork of the `pixi-spine` as a proof of concept. As I've had a few issues with the current implementation. It also removes the use of global `PIXI`
> 
> https://github.com/lucas-jones/pixi-spine

Tried to build your fork but it threw 214 odd errors which I suspect might be something to do with my version of tsc/node?
Here are the details, if it helps: OS: Ubuntu, node: v14.15.0, npm: 6.14.8 and tsc: Version 4.0.5

Do you think you could create a sample repo with the 'Basic Example' code that you pasted on your pixi-spine fork?
The 'Basic Example' is exactly what I want to achieve in my project but currently, I get this error: `"ReferenceError: PIXI is not defined"`, when i do this in my class:
```
import * as PIXI from 'pixi.js';
import 'pixi-spine';
```

**Comment by lucas-jones** [comment]
It's been a while since i've look into this. You got any example of the odd errors? You should just be able to use this:

https://github.com/lucas-jones/pixi-spine/blob/master/README.md

You might also need to add `Loader.registerPlugin(AtlasParser);` after the imports if you get a run-time error when attempting to load the spine file

**Comment by skylarrikin** [comment]
Hey @lucas-jones ,

Thank you for the prompt response.

Here is a screenshot of the errors (they all appear to be 'lodash' related):
![image](https://user-images.githubusercontent.com/66931958/100226998-922bfc00-2f74-11eb-9bf4-e19645c7e1b1.png)

**Comment by lucas-jones** [comment]
Try changing the version of Typescript in the `package.json`

ie: `"typescript": "^3.5.3"`

**Comment by skylarrikin** [comment]
That was very helpful, indeed :+1: 

Thank you very much, @lucas-jones. I was able to compile without any dramas.

Just so that I understand (looking at your code changes), I noticed that you:
1. Removed all instances of '`PIXI`' global namespace usage
2. Removed all instances of '`namespace pixi_spine`' declaration
3. Added `import {xx} from "./x/y/z";` (pixi-spine class imports)
4. And lastly, added `import { Loader, pixijs_ } from "pixi.js"` (core pixi class imports)

Doing the above, I could possibly transform any other pixi based plugin to be ES Module compatible and eliminate the need for Global use of '`PIXI`', is that right? Or did I miss something?

@ivanpopelyshev ~ I realise you are a very busy man, handling lots of projects under your belt, plus helping everyone within the PixiJS community and I have huge admiration and respect for the work that you have been doing. 
Just out of curiosity, when do you foresee these changes made by Lucas to become a part of the official pixi-spine release?

**Comment by skylarrikin** [comment]
Heya @lucas-jones ~ Just to add to my previous comment -

After successfully compiling your fork, I got stuck with not knowing what to do with the build files from the 'bin' folder?
How do I go about using it? Where should I place this 'bin' folder within my project setup?

I have created a sample repo with a basic setup of TypeScript + PixiJS + Pixi-Spine, and have added the 'bin' folder within the 'src' folder. Do you think you could have a look at this dummy repo and provide me with some pointers on how to go about fixing the error?

The error that I get is: 
`src/index.ts(2,23): error TS2306: File '/home/mahesh/RISE/DEV/CLIENT_PLAYGROUND/snowpack-pixijs-pixispine/node_modules/pixi-spine/dist/pixi-spine.d.ts' is not a module.`

I really appreciate your help, mate :).

Thank you.

**Comment by lucas-jones** [comment]
Don't copy the bin folder, you should use [`npm link`](https://docs.npmjs.com/cli/v6/commands/npm-link) to link your local version of the `pixi-spine` (my fork I assume) to your project. _Note: make sure you build pixi-spine._

Once linked you'll also need to add `Loader.registerPlugin(AtlasParser);` before you load the Spine file (This is important to ensure Pixi loaders know how to load Spine files) [Update Example](https://github.com/lucas-jones/pixi-spine/blob/master/README.md)

Note: snowpack caches dependencies so you might need to run it with the `--reload` argument to ensure it's using the freshly linked version

**Comment by ivanpopelyshev** [comment]
We are working on PixiJS 5.4.0 and experimenting on plugin pixi-tilemap to get imports and typescript definitions the right way. For 5.4 I'll have to change ALL my plugins including this one.

**Comment by Friksel** [comment]
> We are working on PixiJS 5.4.0 and experimenting on plugin pixi-tilemap to get imports and typescript definitions the right way. For 5.4 I'll have to change ALL my plugins including this one.

Cool!!

**Comment by skylarrikin** [comment]
@ivanpopelyshev  ~ Thank you very much, kind Sir.

@lucas-jones ~ You have been very helpful, thank you :). I learnt a new trick today (npm link) and not only did it help me setup your fork to playtest but it also gave me a valuable lesson on how to better organize my project dependencies.
Alrighty, so I have updated my [REPO](https://github.com/skylarrikin/snowpack-pixijs-pixispine) with your suggestion and it worked like a charm. 

-----
In case someone else comes to this thread with the same issue that I had, just for their information, there are some limitations of Lucas' fork - **mainly due to the fork being done sometime back**. However, let me reaffirm that what **Lucas contributed works as expected**, i.e., import statements for 'pixi-spine'
1. Lucas' fork supports SPINE 3.7, i.e., no support for .skel files. 
2. The spine objects are rendered as mangled. I am not sure what's gone wrong but here is a screenshot:
![image](https://user-images.githubusercontent.com/66931958/100390744-8f6cfc00-3085-11eb-94c7-be38cee8d181.png)


Thank you, all.
