### ISSUE TITLE
grunt-browserify task fails with latest version when require pixi-spine

### ISSUE THREAD

**Issue by Zenext** [pixijs/pixi-spine#125]
After updating pixi to v4 we decided to update pixi-spine also, but we run into a problem that if you install latest version with npm and then try to run it through grunt-browserify we get following error:

Part of console output:

```
Running "browserify:development" (browserify) task
>> Error: Cannot find module './Utils' from 'C:\project\node_modules\pixi-spine\bin'
Warning: Error running grunt-browserify.
```

**Comment by ivanpopelyshev** [comment]
Oh, right, I dont know how to build that to use require() with it. Can you please clone the repo , "npm link" it locally and see what can we do about it?

**Comment by Zenext** [comment]
Ugh, typescript is completely unknown world for me :) I tried to tweak tsconfig and play with exports but it seems that's it's all fine there. One thing I don't get is why it works fine if you just load pixi-spine.js manually through index.html, but fails if required from node_modules?

**Comment by ivanpopelyshev** [comment]
may be i have to republish it to npm with "src: bin\pixi-spine.js" ?

**Comment by Zenext** [comment]
No luck.

I also forgot to mention that 'browserify-versionify' dependency is missing in dependencies, it's in dev right know.

**Comment by ivanpopelyshev** [comment]
Can you try again please? remove "node_modules" too, I removed all that stuff, the only serious dependency is typescript itself.

**Comment by FFankias** [comment]
hi, I tried with pixi.js 4.2.2 and pixi spine 1.3.2. It seems pixi spine rewrites global pixi object, and when I require("pixi.js") there is only
```
{
 spine: object
}

```
as pixi instance.

**Comment by cursedcoder** [comment]
should be ok now
