### ISSUE TITLE
TypeScript import broken for pixi-spine 2.1.0

### ISSUE THREAD

**Issue by qtiki** [pixijs/pixi-spine#309]
Importing pixi-spine 2.1.0 from TypeScript gives a bunch of errors:
```
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:831:37
    TS2304: Cannot find name 'TransformMode'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:832:36
    TS2304: Cannot find name 'PositionMode'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:833:35
    TS2304: Cannot find name 'SpacingMode'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:834:34
    TS2304: Cannot find name 'RotateMode'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:835:33
    TS2304: Cannot find name 'BlendMode'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:849:27
    TS2304: Cannot find name 'AttachmentLoader'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:852:39
    TS2304: Cannot find name 'AttachmentLoader'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:853:47
    TS2304: Cannot find name 'SkeletonData'.
[at-loader] ./node_modules/pixi-spine/bin/pixi-spine.d.ts:861:28
    TS2304: Cannot find name 'CurveTimeline'.
```

**Comment by martinAnsty** [comment]
I thought at first this was caused by the bump from typescript 2.x to 3.5.3, but having checked everything works correctly in pixi-spine 2.0.5 so it must be something else.

**Comment by ivanpopelyshev** [comment]
ok, here's the problem: https://github.com/pixijs/pixi-spine/blob/master/bin/pixi-spine.d.ts#L828

Gonna fix it today.

**Comment by ivanpopelyshev** [comment]
Published. Try 2.1.1

**Comment by martinAnsty** [comment]
Did you mean to publish to npm? Couldn't see it there but I installed from the github repo and the type errors are fixed. Thanks Ivan

**Comment by qtiki** [comment]
I can confirm that it's fixed in v2.1.1 from npm.

**Comment by ivanpopelyshev** [comment]
@martinAnsty some people take it from NPM some from repo. I update both usually.

**Comment by martinAnsty** [comment]
> @martinAnsty some people take it from NPM some from repo. I update both usually.

I think I just tried to grab it from npm before it was available, 2.1.1 works fine for me now.
